/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package erp;

import erp.loginform.LoginDialog;
import java.awt.Toolkit;
import java.awt.event.ActionListener;

/**
 *
 * @author Arkita
 */
public class ERP_View extends javax.swing.JFrame {

    private int status;
            
    public ERP_View() {
        status = -1;
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/icon.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_logo = new javax.swing.JLabel();
        button_kalendarz = new javax.swing.JButton();
        button_terminarz = new javax.swing.JButton();
        button_pacjenci = new javax.swing.JButton();
        button_personel = new javax.swing.JButton();
        button_komorka = new javax.swing.JButton();
        button_grafik = new javax.swing.JButton();
        button_wizyty = new javax.swing.JButton();
        button_bazadanych = new javax.swing.JButton();
        button_pomoc = new javax.swing.JButton();
        button_konta = new javax.swing.JButton();
        label_license = new javax.swing.JTextField();
        button_logowanie = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        label_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N

        button_kalendarz.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        button_kalendarz.setText("Kalendarz");

        button_terminarz.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        button_terminarz.setText("Terminarz");

        button_pacjenci.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        button_pacjenci.setText("Pacjenci");

        button_personel.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        button_personel.setText("Personel");

        button_komorka.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        button_komorka.setText("Komórka");

        button_grafik.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        button_grafik.setText("Grafik");

        button_wizyty.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        button_wizyty.setText("Wizyty");

        button_bazadanych.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        button_bazadanych.setText("Baza danych");

        button_pomoc.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        button_pomoc.setText("Pomoc");

        button_konta.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        button_konta.setText("Konta");

        label_license.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        label_license.setEnabled(false);

        button_logowanie.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        button_logowanie.setText("Logowanie");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(button_pacjenci, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_kalendarz, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_terminarz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_wizyty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(label_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(label_license, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(button_komorka, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(button_bazadanych, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(button_konta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(button_logowanie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(button_pomoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(button_grafik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(button_personel, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(label_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(button_terminarz, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(button_kalendarz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_pacjenci, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_wizyty, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_komorka, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_personel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_bazadanych, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_grafik, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(button_pomoc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button_konta)
                        .addGap(0, 0, 0)
                        .addComponent(button_logowanie)))
                .addGap(0, 0, 0)
                .addComponent(label_license, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void setTextLog(String text){
        button_logowanie.setText(text);
    }
    public void setLabelLicencja(String text){
        label_license.setText(text);
    }
    public void setEnabledBazaDanych(boolean enabled){
        button_bazadanych.setEnabled(enabled);
    }
    public void setEnabledKonta(boolean enabled){
        button_konta.setEnabled(enabled);
    }
    public void setEnabledLogowanie(boolean enabled){
        button_logowanie.setEnabled(enabled);
    }
    public void setEnabledKalendarz(boolean enabled){
        button_kalendarz.setEnabled(enabled);
    }
    public void setEnabledTerminarz(boolean enabled){
        button_terminarz.setEnabled(enabled);
    }
    public void setEnabledPacjenci(boolean enabled){
        button_pacjenci.setEnabled(enabled);
    }
    public void setEnabledPersonel(boolean enabled){
        button_personel.setEnabled(enabled);
    }
    public void setEnabledKomorka(boolean enabled){
        button_komorka.setEnabled(enabled);
    }
    public void setEnabledGrafik(boolean enabled){
        button_grafik.setEnabled(enabled);
    }
    public void setEnabledWizyty(boolean enabled){
        button_wizyty.setEnabled(enabled);
    }
    
    
    void button_bazadanych(ActionListener listen){
        button_bazadanych.addActionListener(listen);
    }
    void button_konta(ActionListener listen){
        button_konta.addActionListener(listen);
    }
    void button_pomoc(ActionListener listen){
        button_pomoc.addActionListener(listen);
    }
    void button_kalendarz(ActionListener listen){
        button_kalendarz.addActionListener(listen);
    }
    void button_terminarz(ActionListener listen){
        button_terminarz.addActionListener(listen);
    }
    void button_pacjenci(ActionListener listen){
        button_pacjenci.addActionListener(listen);
    }
    void button_personel(ActionListener listen){
        button_personel.addActionListener(listen);
    }
    void button_komorka(ActionListener listen){
        button_komorka.addActionListener(listen);
    }
    void button_grafik(ActionListener listen){
        button_grafik.addActionListener(listen);
    }
    void button_wizyty(ActionListener listen){
        button_wizyty.addActionListener(listen);
    }
    void button_logowanie(ActionListener listen){
        button_logowanie.addActionListener(listen);
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_bazadanych;
    private javax.swing.JButton button_grafik;
    private javax.swing.JButton button_kalendarz;
    private javax.swing.JButton button_komorka;
    private javax.swing.JButton button_konta;
    private javax.swing.JButton button_logowanie;
    private javax.swing.JButton button_pacjenci;
    private javax.swing.JButton button_personel;
    private javax.swing.JButton button_pomoc;
    private javax.swing.JButton button_terminarz;
    private javax.swing.JButton button_wizyty;
    private javax.swing.JTextField label_license;
    private javax.swing.JLabel label_logo;
    // End of variables declaration//GEN-END:variables
}
