/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package erp.komorka;

import erp.ERP_View;
import java.awt.Font;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JFrame;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.text.AbstractDocument;
import library.MyOwnClasses;

/**
 *
 * @author Arkita
 */
public final class KomorkaView extends javax.swing.JFrame {

    /**
     * Creates new form KomorkaView
     */
    ERP_View erp_view;
    
    DefaultTableModel komorki_table_model;
    TableRowSorter<TableModel> komorki_row_sorter;  
    
    public KomorkaView(ERP_View erp_view) {
        this.erp_view = erp_view;
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        table_model_init();
        txtfields_init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        combobox_wizyta = new javax.swing.JComboBox();
        panel_komorka = new javax.swing.JPanel();
        label_nazwa = new javax.swing.JLabel();
        txtfield_nazwa = new javax.swing.JTextField();
        label_adres = new javax.swing.JLabel();
        label_punkty = new javax.swing.JLabel();
        txtfield_punkty = new javax.swing.JTextField();
        label_numer = new javax.swing.JLabel();
        txtfield_numer = new javax.swing.JTextField();
        txtfield_adres = new javax.swing.JTextField();
        button_dodaj = new javax.swing.JButton();
        button_usun = new javax.swing.JButton();
        button_zmien = new javax.swing.JButton();
        button_wyczysc = new javax.swing.JButton();
        label_pln = new javax.swing.JLabel();
        txtfield_pln = new javax.swing.JTextField();
        label_typ = new javax.swing.JLabel();
        combobox_typ = new javax.swing.JComboBox();
        scrollpane_tabela = new javax.swing.JScrollPane();
        table_komorki = new javax.swing.JTable();

        combobox_wizyta.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        combobox_wizyta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));
        combobox_wizyta.setEnabled(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        label_nazwa.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        label_nazwa.setText("Nazwa:");

        txtfield_nazwa.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        label_adres.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        label_adres.setText("Adres:");

        label_punkty.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        label_punkty.setText("Punkty:");

        txtfield_punkty.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        label_numer.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        label_numer.setText("Numer:");

        txtfield_numer.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        txtfield_adres.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        button_dodaj.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        button_dodaj.setText("Dodaj komórkę");

        button_usun.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        button_usun.setText("Usuń komórkę");

        button_zmien.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        button_zmien.setText("Zmień komórkę");

        button_wyczysc.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        button_wyczysc.setText("Wyczyść pola");

        label_pln.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        label_pln.setText("PLN/punkt:");

        txtfield_pln.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        label_typ.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        label_typ.setText("Typ:");

        combobox_typ.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        combobox_typ.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Wybierz", "Poradnia psychiatryczna", "Poradnia psychiatryczna DZiM","Poradnia psychologiczna", "Zespół leczenia środowiskowego" }));

        javax.swing.GroupLayout panel_komorkaLayout = new javax.swing.GroupLayout(panel_komorka);
        panel_komorka.setLayout(panel_komorkaLayout);
        panel_komorkaLayout.setHorizontalGroup(
            panel_komorkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_komorkaLayout.createSequentialGroup()
                .addGroup(panel_komorkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_komorkaLayout.createSequentialGroup()
                        .addGroup(panel_komorkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(label_nazwa, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                            .addComponent(label_adres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_komorkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_komorkaLayout.createSequentialGroup()
                                .addComponent(txtfield_nazwa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label_numer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtfield_numer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtfield_adres))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_komorkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panel_komorkaLayout.createSequentialGroup()
                                .addComponent(label_punkty)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtfield_punkty, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label_pln)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtfield_pln, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_komorkaLayout.createSequentialGroup()
                                .addComponent(label_typ)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(combobox_typ, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(panel_komorkaLayout.createSequentialGroup()
                        .addComponent(button_dodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_usun, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_zmien, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_wyczysc, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panel_komorkaLayout.setVerticalGroup(
            panel_komorkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_komorkaLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(panel_komorkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nazwa)
                    .addComponent(txtfield_nazwa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_numer)
                    .addComponent(txtfield_numer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_punkty)
                    .addComponent(txtfield_punkty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_pln)
                    .addComponent(txtfield_pln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_komorkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_komorkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label_adres)
                        .addComponent(txtfield_adres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label_typ))
                    .addComponent(combobox_typ, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_komorkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_komorkaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(button_wyczysc, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(button_zmien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_usun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_dodaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        table_komorki.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        scrollpane_tabela.setViewportView(table_komorki);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_komorka, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scrollpane_tabela)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_komorka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollpane_tabela, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        erp_view.setEnabled(true);    // TODO add your handling code here:
        erp_view.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    
    public void setUsePunkty(boolean isused){
        txtfield_punkty.setEnabled(isused);
    }
    public void setAdres(String adres) {
        this.txtfield_adres.setText(adres);
    }
    public void setNazwa(String nazwa) {
        this.txtfield_nazwa.setText(nazwa);
    }
    public void setNumer(String numer) {
        this.txtfield_numer.setText(numer);
    }
    public void setPunkty(String punkty) {
        this.txtfield_punkty.setText(punkty);
    }
    public void setPLN(String punkty) {
        this.txtfield_pln.setText(punkty);
    }
    public void setValues(ArrayList<String> values){
        setNazwa(values.get(0));
        setNumer(values.get(1));
        setAdres(values.get(2));
        setPunkty(values.get(3));
    }
    public void buttonsState(boolean status){
        button_usun.setEnabled(status);
        button_zmien.setEnabled(status);
        button_dodaj.setEnabled(!status);
    }
    
    public int getId(int row){
        return Integer.valueOf((String)table_komorki.getValueAt(row, 0));
    }
    public int getTableSelectedRow(){
        return table_komorki.getSelectedRow();
    }
    public String getAdres() {
        return txtfield_adres.getText();
    }
    public String getNazwa() {
        return txtfield_nazwa.getText();
    }
    public String getNumer() {
        return txtfield_numer.getText();
    }
    public String getPunkty(){
        return txtfield_punkty.getText();
    }
    public String getPLN(){
        return txtfield_pln.getText();
    }
    public ArrayList<String> getValues(){
        ArrayList<String> values = new ArrayList<>(Arrays.asList(getNazwa(), getNumer(), getAdres(), getPunkty(), getPLN(), String.valueOf(getTyp())));
        return values;
    }
    public int getTyp(){
        return combobox_typ.getSelectedIndex();
    }
   
    //FUNKCJE
    public void dodaj_wiersz(String id, String nazwa, String numer, String adres, String punkty, String pln){       
        komorki_table_model.addRow(new String[]{id,nazwa,numer,adres,punkty,pln});
    }
    public void wyczysc_tabele(){
       komorki_table_model.setRowCount(0);
    }
    void table_model_init(){     
        komorki_table_model = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
            //all cells false
            return false;
            }
            @Override
            public Class<?> getColumnClass(int columnIndex) {
                return String.class;
            }
        };
        komorki_table_model.addColumn("Id");
        komorki_table_model.addColumn("Nazwa");
        komorki_table_model.addColumn("Numer");
        komorki_table_model.addColumn("Adres");
        komorki_table_model.addColumn("Punkty");    
        komorki_table_model.addColumn("PLN");
        table_komorki.setModel(komorki_table_model);
        table_komorki.getColumn("Id").setWidth(0);
        table_komorki.getColumn("Id").setMaxWidth(0);
        table_komorki.getColumn("Id").setMinWidth(0);
        table_komorki.getColumn("Id").setPreferredWidth(0);
        table_komorki.getColumn("Punkty").setMinWidth(60);
        table_komorki.getColumn("Punkty").setMaxWidth(60);
        table_komorki.getColumn("Numer").setMinWidth(80);
        table_komorki.getColumn("Numer").setMaxWidth(80);
        table_komorki.getColumn("Nazwa").setMinWidth(170);
        table_komorki.getColumn("Nazwa").setMaxWidth(170);
        table_komorki.getColumn("PLN").setMinWidth(40);
        table_komorki.getColumn("PLN").setMaxWidth(40);
        table_komorki.setAutoCreateRowSorter(true); 
        komorki_row_sorter = new TableRowSorter<>(table_komorki.getModel());
        table_komorki.setRowSorter(komorki_row_sorter);
        //table_pacjenci.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);     
        table_komorki.setRowSelectionAllowed(true);
        table_komorki.setDefaultRenderer(String.class, new MyOwnClasses.VisitorRenderer());
        table_komorki.setFont(new Font("Calibri", Font.PLAIN, 14));
        table_komorki.getTableHeader().setFont( new Font( "Calibri", Font.BOLD, 14));
    }        
    void txtfields_init(){
        
    ((AbstractDocument) txtfield_nazwa.getDocument()).setDocumentFilter(new MyOwnClasses.NazwaDocumentFilter());
    ((AbstractDocument) txtfield_numer.getDocument()).setDocumentFilter(new MyOwnClasses.NumerDocumentFilter());
    ((AbstractDocument) txtfield_adres.getDocument()).setDocumentFilter(new MyOwnClasses.AdresDocumentFilter());
    ((AbstractDocument) txtfield_punkty.getDocument()).setDocumentFilter(new MyOwnClasses.CzasDocumentFilter());    
    ((AbstractDocument) txtfield_pln.getDocument()).setDocumentFilter(new MyOwnClasses.CzasDocumentFilter());
    }
    void clear_selection(){
        this.table_komorki.clearSelection();
    }
        
    //EVENTS
    void dodaj_komorke(ActionListener listenForDodajKomorke){
        button_dodaj.addActionListener(listenForDodajKomorke);
    }  
    void zmien_dane(ActionListener listenForZmienDane){
        button_zmien.addActionListener(listenForZmienDane);
    }        
    void usun_komorke(ActionListener listenForUsunKomorke){
        button_usun.addActionListener(listenForUsunKomorke);
    }   
    void wyczysc_pola(ActionListener listenForWyczyscPola){
        button_wyczysc.addActionListener(listenForWyczyscPola);
    }
    void zaznaczono_wiersz(ListSelectionListener listenForZaznaczonoWiersz){
        table_komorki.getSelectionModel().addListSelectionListener(listenForZaznaczonoWiersz);
    }
    void combobox_typ_action(ActionListener listen){
        combobox_typ.addActionListener(listen);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_dodaj;
    private javax.swing.JButton button_usun;
    private javax.swing.JButton button_wyczysc;
    private javax.swing.JButton button_zmien;
    private javax.swing.JComboBox combobox_typ;
    private javax.swing.JComboBox combobox_wizyta;
    private javax.swing.JLabel label_adres;
    private javax.swing.JLabel label_nazwa;
    private javax.swing.JLabel label_numer;
    private javax.swing.JLabel label_pln;
    private javax.swing.JLabel label_punkty;
    private javax.swing.JLabel label_typ;
    private javax.swing.JPanel panel_komorka;
    private javax.swing.JScrollPane scrollpane_tabela;
    private javax.swing.JTable table_komorki;
    private javax.swing.JTextField txtfield_adres;
    private javax.swing.JTextField txtfield_nazwa;
    private javax.swing.JTextField txtfield_numer;
    private javax.swing.JTextField txtfield_pln;
    private javax.swing.JTextField txtfield_punkty;
    // End of variables declaration//GEN-END:variables

}
